import type { PrismaClient } from "@prisma/client";
import type { SecretBox } from "../crypto/secretBox";
import type { SubstackSession } from "../substack";
import { normalizeDomain } from "../substack/types";
import { InvalidInputError } from "../substack/errors";
import type {
  SnapshotInput,
  StoredPublication,
  SyncStore,
  UpsertSubscriberInput,
} from "../sync/types";

export type PrismaStoreDeps = {
  prisma: PrismaClient;
  secretBox: SecretBox;
};

/**
 * Prisma's generated Bytes fields are `Uint8Array<ArrayBuffer>` (TS 5.7+
 * generic typed arrays); `Buffer` is `Buffer<ArrayBufferLike>` and fails that
 * assignment. Copying into a plain Uint8Array produces the ArrayBuffer-backed
 * view Prisma expects.
 */
function toBytes(buffer: Buffer): Uint8Array<ArrayBuffer> {
  return new Uint8Array(buffer);
}

/** Connect flow: create or refresh a publication's encrypted owner cookie. */
export async function upsertPublication(
  deps: PrismaStoreDeps,
  input: { domain: string; session: SubstackSession; cookie: string },
): Promise<StoredPublication> {
  const subdomain = normalizeDomain(input.domain);
  const record = await deps.prisma.publication.upsert({
    where: { substackId: subdomain },
    create: {
      substackId: subdomain,
      subdomain,
      displayName: input.session.displayName ?? subdomain,
      cookieCiphertext: toBytes(deps.secretBox.encrypt(input.cookie)),
      cookieValid: true,
    },
    update: {
      displayName: input.session.displayName ?? subdomain,
      cookieCiphertext: toBytes(deps.secretBox.encrypt(input.cookie)),
      cookieValid: true,
    },
  });
  return {
    id: record.id,
    subdomain: record.subdomain,
    displayName: record.displayName,
    cookieCiphertext: record.cookieCiphertext,
    cookieValid: record.cookieValid,
  };
}

/**
 * Sync flow: identity upsert keyed on (publication, substackUserId), so
 * re-running a sync never duplicates subscribers — the idempotency the spec
 * requires. Emails are encrypted and HMAC-hashed here, at the persistence
 * boundary; the pipeline never sees key material.
 */
async function upsertSubscriber(
  deps: PrismaStoreDeps,
  input: UpsertSubscriberInput,
): Promise<string> {
  // The seam skips feed rows without a user id, so this only fires on misuse.
  if (!input.substackUserId) {
    throw new InvalidInputError("subscriber upsert requires a substack user id");
  }
  const emailCiphertext = input.email ? deps.secretBox.encrypt(input.email) : null;
  const emailHash = input.email ? deps.secretBox.hash(input.email) : null;

  const subscriber = await deps.prisma.subscriber.upsert({
    where: {
      publicationId_substackUserId: {
        publicationId: input.publicationId,
        substackUserId: input.substackUserId,
      },
    },
    create: {
      publicationId: input.publicationId,
      substackUserId: input.substackUserId,
      handle: input.handle,
      displayName: input.displayName,
      emailCiphertext: emailCiphertext ? toBytes(emailCiphertext) : null,
      emailHash,
      subscribedAt: input.subscribedAt,
    },
    update: {
      handle: input.handle ?? undefined,
      displayName: input.displayName ?? undefined,
      emailCiphertext: emailCiphertext ? toBytes(emailCiphertext) : undefined,
      emailHash: emailHash ?? undefined,
      subscribedAt: input.subscribedAt ?? undefined,
    },
  });
  return subscriber.id;
}

/** Snapshots are append-only: create only, never update, never delete. */
async function appendSnapshot(
  deps: PrismaStoreDeps,
  input: Omit<SnapshotInput, "id">,
): Promise<void> {
  await deps.prisma.subscriberSnapshot.create({
    data: {
      subscriberId: input.subscriberId,
      capturedAt: input.capturedAt,
      subscriberCount: input.subscriberCount,
      bestsellerStatus: input.bestsellerStatus,
      activityRating: input.activityRating,
      source: input.source,
    },
  });
}

export function createPrismaStore(deps: PrismaStoreDeps): SyncStore {
  return {
    findPublicationByDomain: async (subdomain) => {
      const record = await deps.prisma.publication.findUnique({
        where: { substackId: subdomain },
      });
      return record
        ? {
            id: record.id,
            subdomain: record.subdomain,
            displayName: record.displayName,
            cookieCiphertext: record.cookieCiphertext,
            cookieValid: record.cookieValid,
          }
        : null;
    },
    upsertSubscriber: (input) => upsertSubscriber(deps, input),
    appendSnapshot: (input) => appendSnapshot(deps, input),
    appendRun: async (input) => {
      await deps.prisma.syncRun.create({ data: input });
    },
  };
}

/** Route helper: load a publication by primary key (null when unknown). */
export async function findPublicationById(
  deps: PrismaStoreDeps,
  id: string,
): Promise<StoredPublication | null> {
  const record = await deps.prisma.publication.findUnique({ where: { id } });
  return record
    ? {
        id: record.id,
        subdomain: record.subdomain,
        displayName: record.displayName,
        cookieCiphertext: record.cookieCiphertext,
        cookieValid: record.cookieValid,
      }
    : null;
}

/** Route helper: records a session as rejected after a 401/403 from upstream. */
export async function markCookieInvalid(
  deps: PrismaStoreDeps,
  publicationId: string,
): Promise<void> {
  await deps.prisma.publication.update({
    where: { id: publicationId },
    data: { cookieValid: false },
  });
}
